server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://db:3306/citytask?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: qboyedison77

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
