server:
  port: 8088

spring:
  datasource:
    url: jdbc:mysql://122.51.211.133:3306/citytask?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: root
    password: root

mybatis:
  mapper-locations:
    - classpath:mapper/*.xml
    - classpath*:com/**/mapper/*.xml
